### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by kelemenlajos** [jacobsjo/windy-plugin-sun-position#1]
Dear Developer!

This plugin is not working for me.
After setting the weatherpicker, i'm opening the plugin, and getting the following error:

```
{
  "timestamp": 1601621277261,
  "runningMs": 14998,
  "type": "user",
  "module": "tinyrequire",
  "msg": "DI error: Can not resolve @plugins/windy-plugin-sun-position module: Tinyrequire error: Module \"pluginDataLoader\" does not exist!",
  "url": "https://www.windy.com/-Rain-thunder-rain?rain,47.361,18.940,8,m:eYragGQ",
  "ver": "27.0.2",
  "target": "index",
  "stack": "Error: Tinyrequire error: Module \"pluginDataLoader\" does not exist!
		    at Object.e.require (https://www.windy.com/v/27.0.2.ind.f945/index.js:9:625)
		    at Object.<anonymous> (https://unpkg.com/windy-plugin-sun-position:31:28)
		    at i (https://www.windy.com/v/27.0.2.ind.f945/index.js:9:415)
		    at Object.e.require (https://www.windy.com/v/27.0.2.ind.f945/index.js:9:716)
		    at Object._mount (https://www.windy.com/v/27.0.2.ind.f945/index.js:67:1179)
		    at https://www.windy.com/v/27.0.2.ind.f945/index.js:67:644",
  "deviceID": "d7820630-be2e-19e2-2ecb-c0201976c780",
  "error": "<Error> {
		    \"stack\": \"Error: Tinyrequire error: Module \\\"pluginDataLoader\\\" does not exist!\
		    at Object.e.require (https://www.windy.com/v/27.0.2.ind.f945/index.js:9:625)\
		    at Object.<anonymous> (https://unpkg.com/windy-plugin-sun-position:31:28)\
		    at i (https://www.windy.com/v/27.0.2.ind.f945/index.js:9:415)\
		    at Object.e.require (https://www.windy.com/v/27.0.2.ind.f945/index.js:9:716)\
		    at Object._mount (https://www.windy.com/v/27.0.2.ind.f945/index.js:67:1179)\
		    at https://www.windy.com/v/27.0.2.ind.f945/index.js:67:644\",
		    \"message\": \"Tinyrequire error: Module \\\"pluginDataLoader\\\" does not exist!\"
		}",
  "isOnline": true,
  "latestBcast": "bcast: externalPluginLoaded windy-plugin-sun-position (2022ms ago at 1601621275239)
		pluginLoader : windy-plugin-sun-position-ok <hr>W.loadPlugin method called<hr>{
		  \"name\": \"windy-plugin-sun-position\",
		  \"version\": \"0.3.1\",
		  \"author\": \"Jochen Jacobs\",
		  \"repository\": {
		    \"type\": \"git\",
		    \"url\": \"git+https://github.com/jacobsjo/windy-plugin-sun-position\"
		  },
		  \"description\": \"Windy plugin that gives shows sun position on the map and gives details about sunset and sunrise times.\",
		  \"displayName\": \"Sun Position\",
		  \"hook\": \"contextmenu\",
		  \"dependencies\": [
		    \"https://unpkg.com/d3@5.7.0/dist/d3.min.js\",
		    \"https://unpkg.com/suncalc@1.8.0/suncalc.js\"
		  ],
		  \"className\": \"plugin-lhpane plugin-mobile-fullscreen\",
		  \"classNameMobile\": \"plugin-sun-position-mobile\",
		  \"exclusive\": \"lhpane\"
		}<hr>Broadcasting externalPluginLoaded<hr>All DONE your plugin is ready to be opened (2022ms ago at 1601621275239)
		bcast: rqstClose plugins (2022ms ago at 1601621275239)
		bcast: pluginClosed plugins (1521ms ago at 1601621275740)
		bcast: rqstOpen windy-plugin-sun-position (20ms ago at 1601621277241)",
  "sessionName": "hu-kelemenlajos",
  "sessionCounter": 17,
  "lang": "en",
  "retina": false,
  "size": "2560x1440",
  "glParticles": true,
  "platform": "desktop",
  "errorID": "di-error-can-not-resolve-pluginswindy-plugin-sun-position"
}
```

br,
Lajos

**Comment by jacobsjo** [comment]
Sorry about the delay, but it is fixed now. The problem was that I used the windy plugin data loader for timezone lookup. Some changes to the plugin data loader have broken it. As that wasn't a good solution anyway I am now using the tz-lookup package instead. So hopefully it wont break as easily in the future. Will publish the fixed version soon.
